version: '2.3'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:3.6.11'
    hostname: mongodb-primary
    networks:
      - internal
    user: root
    ports:
    - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    volumes:
      - '/mongo/:/bitnami/mongodb'


  mongodb-secondary:
    image: 'docker.io/bitnami/mongodb:3.6.11'
    hostname: mongodb-secondary
    networks:
      - internal
    user: root
    ports:
    - 27018:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123



  mongodb-arbiter:
    image: 'docker.io/bitnami/mongodb:3.6.11'
    hostname: mongodb-arbiter
    user: root
    networks:
      - internal
    ports:
    - 27019:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter    
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_RIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123



networks:
  internal:
